soulfeeling/groups/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),

    url(r"contactUs/$",views.contactUsPage.as_view(),name="contactUs"),
    url(r"feedBack/$",views.feedBackPage.as_view(),name="feedBack"),
    url(r"fieldInformation/$",views.fieldInformationPage.as_view(),name="fieldInformation"),
    url(r"offlineStore_newestStore/$",views.offlineStore_newestStorePage.as_view(),name="offlineStore_newestStore"),
    url(r"offlineStore_onlyOnePage/$",views.offlineStore_onlyOnePagePage.as_view(),name="offlineStore_onlyOnePage"),
    url(r"offlineStore_policy/$",views.offlineStore_policyPage.as_view(),name="offlineStore_policy"),
    url(r"offlineStore/$",views.offlineStorePage.as_view(),name="offlineStore"),
    url(r"productContent/$",views.productContentPage.as_view(),name="productContent"),
    url(r"secondPageContent/$",views.secondPageContentPage.as_view(),name="secondPageContent"),
    url(r"newsInformation/$",views.newsInformationPage.as_view(),name="newsInformation"),
    url(r"video/$",views.VideoPage.as_view(),name="video"),
    url(r"join/$",views.joinPage.as_view(),name="join"),

    url(r"feedBack_afterMarketPolicy/$",views.feedBackPage_afterMarketPolicy.as_view(),name="feedBack_afterMarketPolicy"),
    url(r"feedBack_deliver/$",views.feedBackPage_deliver.as_view(),name="feedBack_deliver"),
    url(r"feedBack_feedBackTable/$",views.feedBackPage_feedBackTable.as_view(),name="feedBack_feedBackTable"),
    url(r"feedBack_shop/$",views.feedBackPage_shop.as_view(),name="feedBack_shop"),
]

soulfeeling/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

soulfeeling/soulfeeling/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="index"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r"^onlinemessages/", include('onlinemessages.urls', namespace="onlinemessages")),
]

soulfeeling/groups/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
# from accounts.models import User

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()



class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships")
    user = models.ForeignKey(User,related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")



class Post(models.Model):
    title = models.CharField(max_length=128)
    body = models.CharField(max_length=400)
    body_html = models.TextField(editable=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.body_html = misaka.html(self.body)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:singlePost", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["title"]

def get_image_filename(instance, filename):
        title = instance.post.title
        slug = slugify(title)
        return "post_images/%s-%s" % (slug, filename)  

class Images(models.Model):
    post = models.ForeignKey(Post, default=None)
    image = models.ImageField(upload_to=get_image_filename,
                              verbose_name='Image', )

soulfeeling/posts/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

import misaka

from groups.models import  Group

from django.contrib.auth import get_user_model
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts")
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

soulfeeling/groups/forms.py
from django import forms

from groups import models

class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=128)
    body = forms.CharField(max_length=245, label="Item Description.")

    class Meta:
        model = models.Post
        fields = ('title', 'body', )


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')    
    class Meta:
        model = models.Images
        fields = ('image', )

soulfeeling/posts/forms.py
from django import forms

from posts import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

soulfeeling/groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from groups.models import Group,GroupMember
from . import models
from django.views.generic import TemplateView

from braces.views import SelectRelatedMixin

from . import forms

from django.contrib.auth.decorators import login_required

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)


class contactUsPage(TemplateView):
    template_name = 'groups/contactUs.html'

class VideoPage(TemplateView):
    template_name = 'groups/video.html'

class feedBackPage(TemplateView):
    template_name = 'groups/feedBack.html'

class feedBackPage_afterMarketPolicy(TemplateView):
    template_name = 'groups/feedBack_afterMarketPolicy.html'

class feedBackPage_deliver(TemplateView):
    template_name = 'groups/feedBack_deliver.html'

class feedBackPage_feedBackTable(TemplateView):
    template_name = 'groups/feedBack_feedBackTable.html'

class feedBackPage_shop(TemplateView):
    template_name = 'groups/feedBack_shop.html'

class fieldInformationPage(TemplateView):
    template_name = 'groups/fieldInformation.html'


class offlineStore_newestStorePage(TemplateView):
    template_name = 'groups/offlineStore_newestStore.html'


class offlineStore_onlyOnePagePage(TemplateView):
    template_name = 'groups/offlineStore_onlyOnePage.html'


class offlineStore_policyPage(TemplateView):
    template_name = 'groups/offlineStore_policy.html'


class offlineStorePage(TemplateView):
    template_name = 'groups/offlineStore.html'

class joinPage(TemplateView):
    template_name = 'groups/join.html'

class productContentPage(TemplateView):
    template_name = 'groups/productContent.html'


class secondPageContentPage(TemplateView):
    template_name = 'groups/secondPageContent.html'

class newsInformationPage(TemplateView):
    template_name = 'groups/newsInformation.html'


from django.forms import modelform_factory

@login_required
def post(request):

    ImageFormSet = modelformset_factory(Images,
                                        form=ImageForm, extra=3)

    if request.method == 'POST':

        postForm = PostForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Images.objects.none())


        if postForm.is_valid() and formset.is_valid():



            post_form = postForm.save(commit=False)
            post_form.user = request.user
            post_form.save()

            for form in formset.cleaned_data:
                image = form['image']
                photo = Images(post=post_form, image=image)
                photo.save()
            messages.success(request,
                             "Yeeew,check it out on the home page!")
            return HttpResponseRedirect("/")
        else:
            print(postForm.errors, formset.errors)
    else:
        postForm = PostForm()
        formset = ImageFormSet(queryset=Images.objects.none())
    return render(request, 'index.html',
                  {'postForm': postForm, 'formset': formset},
                  context_instance=RequestContext(request))

soulfeeling/posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    fields = ('message','group')
    model = models.Post

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs.update({"user": self.request.user})
    #     return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

soulfeeling/groups/templates/groups/fieldInformation.html
{% extends "base.html" %}
{% load staticfiles %}
{% block customeCSSContent %}
<link rel="stylesheet" href="{% static "css/offlineStore.css" %}">
{% endblock %}

{% block content %}

<div class="div-fullWidth">
        <div class="textStyle">
            <div>
                极速先锋模拟竞速大赛
                <br />
                与F1车手一起同步夺冠
            </div>
            <div class="separate">
                SPEED PIONEER SIMULATED RACING COMPETTION
                <br />
                WIN WITH F1 DRIVER SIMULTANEOUSLY
            </div>
            <div class="more">
                <a href="{% url 'groups:newsInformation' %}">
                    <img src="{% static "image/FieldInfo/more.png" %}" />
                </a>
            </div>
        </div>
        <img id="newsImg" src="{% static "image/FieldInfo/newHeader.png" %}">
    </div>

    <div id="offline-all-news">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link active">行业动态</a>
            </li>
            <li class="nav-item">
                <a class="nav-link">公司动态</a>
            </li>
            <li class="nav-item">
                <a class="nav-link">加盟动态</a>
            </li>
        </ul>
    </div>

	<div id="offline-Activity">
        <div class="listActivity">
            <div class="activePicture">
                <img src="{% static "image/offlineStore/store.png" %}"/>
            </div>
            <div class="newsInfo">
                <h4>幻速荣获亚洲VR博览会年度VR技术创新奖</h4>
                <br/>
                <div>
                    近日，中国体感科技领跑者X-MOTION旗下幻速赛车模拟器正式加入VR创新组织ChinaVRjoy,
                    并于5月13日受邀参加ChianVRjoy在武汉举办的中国VR应用开发者大赛。
                </div>
            </div>
            <div class="date">
                <h3>10-20</h3>
                <h5>2016</h5>
            </div>
        </div>
        <div class="clear"></div>
        <div class="listActivity">
            <div class="activePicture">
                <img src="{% static "image/offlineStore/store.png" %}" />
            </div>
            <div class="newsInfo">
                <h4>幻速荣获亚洲VR博览会年度VR技术创新奖</h4>
                <br />
                <div>
                    近日，中国体感科技领跑者X-MOTION旗下幻速赛车模拟器正式加入VR创新组织ChinaVRjoy,
                    并于5月13日受邀参加ChianVRjoy在武汉举办的中国VR应用开发者大赛。
                </div>
            </div>
            <div class="date">
                <h3>10-20</h3>
                <h5>2016</h5>
            </div>
        </div>
        <div class="clear"></div>
        <div class="listActivity">
            <div class="activePicture">
                <img src="{% static "image/offlineStore/store.png" %}" />
            </div>
            <div class="newsInfo">
                <h4>幻速荣获亚洲VR博览会年度VR技术创新奖</h4>
                <br />
                <div>
                    近日，中国体感科技领跑者X-MOTION旗下幻速赛车模拟器正式加入VR创新组织ChinaVRjoy,
                    并于5月13日受邀参加ChianVRjoy在武汉举办的中国VR应用开发者大赛。
                </div>
            </div>
            <div class="date">
                <h3>10-20</h3>
                <h5>2016</h5>
            </div>
        </div>
        <div class="clear"></div>
        <div class="listActivity">
            <div class="activePicture">
                <img src="{% static "image/offlineStore/store.png" %}" />
            </div>
            <div class="newsInfo">
                <h4>幻速荣获亚洲VR博览会年度VR技术创新奖</h4>
                <br />
                <div>
                    近日，中国体感科技领跑者X-MOTION旗下幻速赛车模拟器正式加入VR创新组织ChinaVRjoy,
                    并于5月13日受邀参加ChianVRjoy在武汉举办的中国VR应用开发者大赛。
                </div>
            </div>
            <div class="date">
                <h3>10-20</h3>
                <h5>2016</h5>
            </div>
        </div>
    </div>

    <div class="clear"></div>

    <div class="div-fullWidth margin_top" id="pagination-div">
        <nav aria-label="Page navigation example" id="pagination-nav">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link"  aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" >1</a>
                </li>
                <li class="page-item">
                    <a class="page-link" >2</a>
                </li>
                <li class="page-item">
                    <a class="page-link" >3</a>
                </li>
                <li class="page-item">
                    <a class="page-link" >4</a>
                </li>
                <li class="page-item">
                    <a class="page-link" >5</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link">......</a>
                </li>
                <li class="page-item">
                    <a class="page-link" >10</a>
                </li>
                <li class="page-item">
                    <a class="page-link" >11</a>
                </li>
                <li class="page-item">
                    <a class="page-link"  aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>

{% endblock %}

soulfeeling/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

soulfeeling/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}


<h1>{{group.name}}</h1>
<h2> Member Count: {{group.members.count}}</h2>

  <div class="content">


				{% if user in group.members.all %}
					<a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
				{% else %}
					<a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
				{% endif %}



</div>

{% endblock %}


{% block group_content %}

<div class="col-md-8">
	{% if group.posts.count == 0 %}
	<h2>No posts in this group yet!</h2>

	{% else %}

		{% for post in group.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}

	{% endif %}
</div>
{% endblock %}

soulfeeling/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create A New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

soulfeeling/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Groups</h2>

			<p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		  <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

soulfeeling/groups/templates/groups/post.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create A New Group</h4>
<form id="post_form" method="post" action=""
      enctype="multipart/form-data">

    {% csrf_token %}
    {% for hidden in postForm.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in postForm %}
        {{ field }} <br />
    {% endfor %}

    {{ formset.management_form }}
    {% for form in formset %}
        {{ form }}
    {% endfor %}


    <input type="submit" name="submit" value="Submit" />
</form>
{% endblock %}

soulfeeling/groups/templates/groups/secondPageContent.html
{% extends "base_without_soulfeeling.html" %}
{% load staticfiles %}
{% block customeCSSContent %}
<link rel="stylesheet" href="{% static "css/secondPage.css" %}">
{% endblock %}

{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div id="img-container">
                <img class="d-block w-100" src="{% static "image/SecondPage/Slide/1.png" %}" alt="First slide" id="first-slide">
                <a href="{% url 'groups:video' %}">
                    <img src="{% static "img/video.png" %}" id="video">
                </a>
				<a href="{% url 'groups:productContent' %}">
					<img src="{% static "img/productDetails.png" %}" id="product-detail">
				</a>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static "image/SecondPage/Slide/1.png" %}" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static "image/SecondPage/Slide/1.png" %}" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
     data-slide="prev">
        <span class="carousel-control-prev-icon" style="background-image:url({% static "img/arrow-left.png" %})" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
     data-slide="next">
        <span class="carousel-control-next-icon" style="background-image:url({% static "img/arrow-right.png" %})" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div>
        <ul class="ulstyle">
            <li class="listyle">
                <a href="{% url 'groups:productContent' %}">
                    <div class="news">
                        <img src="{% static "image/SecondPage/new1.png" %}" class="imgstyle" />
                        <div class="newsText">
                            <strong>体感/VR/力反馈</strong>
                            <hr class="hrClass"/>
                            了解幻速专业设计与全新科技
                        </div>
                    </div>
                </a>
            </li>
            <li class="new2 listyle">
                <a href="{% url 'groups:offlineStore_onlyOnePage' %}">
                    <div class="news">
                        <img src="{% static "image/SecondPage/new2.png" %}" class="imgstyle" />
                        <div class="newsText">
                            <strong>全国线下体验店</strong>
                            <hr class="hrClass" />
                            踩过油门，才懂得速度。尝试漂移，身体力行。
                        </div>
                    </div>
                </a>
            </li>
            <li class="listyle">
                <a href="">
                    <div class="news">
                        <img src="{% static "image/SecondPage/new3.png" %}" class="imgstyle" />
                        <div class="newsText">
                            <strong>主题挑战赛</strong>
                            <hr class="hrClass" />
                            挑战全世界的赛车手
                        </div>
                    </div>
                </a>
            </li>
        </ul>
    </div>
    <div class="clear"></div>

{% endblock %}

soulfeeling/groups/templates/groups/video.html
{% extends "base_without_soulfeeling.html" %}
{% load staticfiles %}
{% block customeCSSContent %}
<link rel="stylesheet" href="{% static "css/video.css" %}">
{% endblock %}

{% block content %}
	<div>
        <video controls autoplay loop>
            <source src="{% static "video/1.mp4" %}" type="video/mp4"> </source>
        </video>
    </div>
{% endblock %}