soulfeeling/accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views
from . import forms

app_name = 'accounts'

urlpatterns = [
    url(r"login/$",auth_views.LoginView.as_view(template_name="accounts/login.html") ,name='login'),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^special/',views.special,name='special'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

soulfeeling/groups/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),

    url(r"contactUs/$",views.contactUsPage.as_view(),name="contactUs"),
    url(r"feedBack/$",views.feedBackPage.as_view(),name="feedBack"),
    url(r"fieldInformation/$",views.fieldInformationPage.as_view(),name="fieldInformation"),
    url(r"offlineStore_newestStore/$",views.offlineStore_newestStorePage.as_view(),name="offlineStore_newestStore"),
    url(r"offlineStore_onlyOnePage/$",views.offlineStore_onlyOnePagePage.as_view(),name="offlineStore_onlyOnePage"),
    url(r"offlineStore_policy/$",views.offlineStore_policyPage.as_view(),name="offlineStore_policy"),
    url(r"offlineStore/$",views.offlineStorePage.as_view(),name="offlineStore"),
    url(r"productContent/$",views.productContentPage.as_view(),name="productContent"),
    url(r"secondPageContent/$",views.secondPageContentPage.as_view(),name="secondPageContent"),
    url(r"newsInformation/$",views.newsInformationPage.as_view(),name="newsInformation"),
    url(r"video/$",views.VideoPage.as_view(),name="video"),
    url(r"join/$",views.joinPage.as_view(),name="join"),

    url(r"feedBack_afterMarketPolicy/$",views.feedBackPage_afterMarketPolicy.as_view(),name="feedBack_afterMarketPolicy"),
    url(r"feedBack_deliver/$",views.feedBackPage_deliver.as_view(),name="feedBack_deliver"),
    url(r"feedBack_feedBackTable/$",views.feedBackPage_feedBackTable.as_view(),name="feedBack_feedBackTable"),
    url(r"feedBack_shop/$",views.feedBackPage_shop.as_view(),name="feedBack_shop"),
]

soulfeeling/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

soulfeeling/soulfeeling/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="index"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r"^onlinemessages/", include('onlinemessages.urls', namespace="onlinemessages")),
]

soulfeeling/templates/base.html
{% extends "base_without_soulfeeling.html" %}
{% load staticfiles %}

{% block soulFeeling %}
<div id="soulFeeling">
    <img id="soulFeelingImg" src="{% static "img/product.png" %}">
</div>
{% endblock %}

soulfeeling/templates/base_backup.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                      <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</html>

soulfeeling/templates/base_without_soulfeeling.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <!--<link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">-->
     <link rel="stylesheet" href="{% static "bootstrap4000/bootstrap.min.css" %}">
     <script src="{% static "bootstrap4000/jquery-3.2.1.slim.min.js" %}"></script>
     <script src="{% static "bootstrap4000/popper.min.js" %}"></script>
     <script src="{% static "bootstrap4000/bootstrap.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "css/mainScreen.css" %}">
    <link rel="shortcut icon" href="{% static "img/logo.png" %}" type="image/x-icon" />
    {% block customeCSSContent %}

    {% endblock %}
</head>
<body>
    <header class="navbar navbar-expand flex-column flex-md-row bd-navbar" id="header-main">
        <a id="header-logo" class="navbar-brand mr-0 mr-md-2" href="/" aria-label="Bootstrap">
            <img src="{% static "img/logo.png" %}">
        </a>
        <div class="navbar-nav-scroll">
            <ul class="navbar-nav bd-navbar-nav flex-row">
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'groups:secondPageContent' %}" >幻速赛车</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'groups:offlineStore' %}" >线下体验店</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'groups:contactUs' %}" >服务</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link"  target="_blank" rel="noopener">社区</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'onlinemessages:create' %}">在线留言</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" rel="noopener">社区</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:user_login' %}">在线留言</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link p-2" href="{% url 'groups:join' %}" target="_blank" rel="noopener" aria-label="Twitter">
                            加盟体验店
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link p-2" target="_blank" rel="noopener" aria-label="Twitter">
                            <input id="searchText" type="text" placeholder="新闻标题" style="display:none" />
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link p-2" target="_blank" rel="noopener" aria-label="Twitter">
                            <img id="searchButton" src="{% static "img/search.png" %}">
                        </a>
                        <script type="text/javascript">
                            $("#searchButton").click(function (e) {
                                var ele = document.getElementById("searchText");

                                if (ele.style.display == "block")
                                {
                                    var title = "幻速荣获亚洲VR博览会年度VR技术创新奖";
                                    var titleValue = $(searchText).val();
                                    if(title.includes(titleValue))
                                    {
                                        $(location).attr('href', "{% url 'groups:newsInformation' %}")
                                    }
                                }
                                else
                                {
                                    ele.style.display = 'block';
                                }
                            });
                        </script>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link p-2" href="{% url 'accounts:user_login' %}" target="_blank" rel="noopener" aria-label="Twitter">
                            加盟体验店
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link p-2" href="{% url 'accounts:user_login' %}" target="_blank" rel="noopener" aria-label="Twitter">
                            <img src="{% static "img/search.png" %}">
                        </a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-item nav-link  mr-md-2" href="#" id="bd-versions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{% static "img/user.png" %}">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">
                            <a class="dropdown-item active" href="{% url 'accounts:logout' %}">登出</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-item nav-link  mr-md-2" href="#" id="bd-versions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{% static "img/user.png" %}">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">
                            <a class="dropdown-item active" href="{% url 'accounts:login' %}">登录</a>
                            <a class="dropdown-item" href="{% url 'accounts:signup' %}">注册</a>
                        </div>
                    </li>
                {% endif %}
        </ul>
    </header>
    
    {% block content %}

    {% endblock %}

    {% block soulFeeling %}

    {% endblock %}

    <footer id="footer-main">
        <section class="links">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h6>关于我们</h6>
                        <ul class="list-unstyled">
                            <li>
                                <a href="{% url 'groups:productContent' %}">产品简介</a>
                            </li>
                            <li>
                                <a href="{% url 'groups:contactUs' %}">联系我们</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col">
                        <h6>新闻中心</h6>
                        <ul class="list-unstyled">
                            <li>
                                <a href="{% url 'groups:fieldInformation' %}">行业动态</a>
                            </li>
                            <li>
                                <a href="{% url 'groups:fieldInformation' %}">公司动态</a>
                            </li>
                            <li>
                                <a href="{% url 'groups:fieldInformation' %}">加盟动态</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col">
                        <h6>线下体验店</h6>
                        <ul class="list-unstyled">
                            <li>
                                <a href="{% url 'groups:offlineStore' %}">最新门店</a>
                            </li>
                            <li>
                                <a href="{% url 'groups:offlineStore_newestStore' %}">全部门店</a>
                            </li>
                            <li>
                                <a href="{% url 'groups:offlineStore_policy' %}">优惠政策</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col">
                        <h6>客服支持</h6>
                        <ul class="list-unstyled">
                            <li>
                                <a href="{% url 'groups:feedBack' %}">售后服务</a>
                            </li>
                            <li>
                                <a href="">联系客服</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col">
                        <ul class="list-unstyled">
                            <li>
                                <img src="{% static "img/wechat.png" %}">
                                <img src="{% static "img/微博.png" %}">
                                <img src="{% static "img/优酷.png" %}">
                            </li>
                        </ul>
                        <h5>0529-5022711</h5>
                    </div>
                </div>
            </div>
        </section>
        <div class="copyright">
            Copyright©2017 幻速Soulfeeling 版权所有
        </div>
    </footer>
</body>
</html>

soulfeeling/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>
    <h2>The best community for all things on outer space!</h2>
    <h2>Login or Sign-up for free to get started!</h2>


{% endblock %}

soulfeeling/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>


</div>




{% endblock %}

soulfeeling/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}